### ISSUE TITLE
[bug] enhance match case

### ISSUE THREAD

**Issue by SoonIter** [devongovett/glob-match#4]
```rust
assert!(glob_match("**/y.txt", "y.txt"));  				// panic
assert!(glob_match("**/package.json", "package.json"));   	 // panic
assert!(glob_match("**/{package}.json", "package.json"));	 // true
``` 
Maybe this should work.

**Comment by devongovett** [comment]
All of those seem to pass with the latest version. Do you still see an issue?

**Comment by SoonIter** [comment]
> All of those seem to pass with the latest version. Do you still see an issue?

Looks good, and take my star 😆
